# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-27 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clase_cuenta', models.CharField(choices=[('MTA', 'Meta'), ('EFE', 'Efectivo'), ('ING', 'Ingreso'), ('GTO', 'Gasto')], max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clase_trans', models.CharField(choices=[('TRA', 'Traspaso'), ('ING', 'Ingreso'), ('GTO', 'Gasto')], max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fecha', models.DateField(null=True)),
                ('notas', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('a_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_destino', to='tracking.Cuenta')),
                ('de_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_origen', to='tracking.Cuenta')),
            ],
        ),
    ]
