# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-28 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_transaccion_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='tipo_cuenta',
            field=models.CharField(choices=[('HON', 'Honorarios'), ('DEP', 'Deporte'), ('BAN', 'Cuenta Bancaria'), ('CAR', 'Cartera'), ('TDC', 'Tarjeta de Crédito'), ('ENT', 'Entretenimiento'), ('AHO', 'Cuenta de Ahorro'), ('ROP', 'Ropa'), ('REN', 'Rendimiento inversiones'), ('ALI', 'Alimentos'), ('ACC', 'Accesorios'), ('OTR', 'Otro'), ('INV', 'Cuenta de Inversiones'), ('NOM', 'Cuenta de Nómina'), ('VID', 'Videojuegos'), ('SAL', 'Salario'), ('APU', 'Apuestas')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='clase_cuenta',
            field=models.CharField(choices=[('ING', 'Ingreso'), ('GTO', 'Gasto'), ('EFE', 'Efectivo'), ('MTA', 'Meta')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='clase_trans',
            field=models.CharField(choices=[('ING', 'Ingreso'), ('GTO', 'Gasto'), ('TRA', 'Traspaso')], max_length=100),
        ),
    ]
