# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-28 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_transaccion_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='clase_cuenta',
            field=models.CharField(choices=[('GTO', 'Gasto'), ('MTA', 'Meta'), ('ING', 'Ingreso'), ('EFE', 'Efectivo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='clase_trans',
            field=models.CharField(choices=[('TRA', 'Traspaso'), ('GTO', 'Gasto'), ('ING', 'Ingreso')], max_length=100),
        ),
    ]
