# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-28 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_auto_20170528_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='clase_cuenta',
            field=models.CharField(choices=[('EFE', 'Efectivo'), ('MTA', 'Meta'), ('GTO', 'Gasto'), ('ING', 'Ingreso')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipo_cuenta',
            field=models.CharField(choices=[('VID', 'Videojuegos'), ('ACC', 'Accesorios'), ('ENT', 'Entretenimiento'), ('NOM', 'Cuenta de Nómina'), ('CAR', 'Cartera'), ('ROP', 'Ropa'), ('INV', 'Cuenta de Inversiones'), ('SAL', 'Salario'), ('TDC', 'Tarjeta de Crédito'), ('APU', 'Apuestas'), ('REN', 'Rendimiento inversiones'), ('OTR', 'Otro'), ('BAN', 'Cuenta Bancaria'), ('DEP', 'Deporte'), ('AHO', 'Cuenta de Ahorro'), ('ALI', 'Alimentos'), ('HON', 'Honorarios')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='clase_trans',
            field=models.CharField(choices=[('TRA', 'Traspaso'), ('GTO', 'Gasto'), ('ING', 'Ingreso')], max_length=100),
        ),
    ]
