# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-28 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_auto_20170528_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='clase_cuenta',
            field=models.CharField(choices=[('ING', 'Ingreso'), ('GTO', 'Gasto'), ('MTA', 'Meta'), ('EFE', 'Efectivo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='clase_trans',
            field=models.CharField(choices=[('ING', 'Ingreso'), ('GTO', 'Gasto'), ('TRA', 'Traspaso')], max_length=100),
        ),
    ]
