# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-28 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_auto_20170528_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='clase_cuenta',
            field=models.CharField(choices=[('MTA', 'Meta'), ('EFE', 'Efectivo'), ('GTO', 'Gasto'), ('ING', 'Ingreso')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='clase_trans',
            field=models.CharField(choices=[('TRA', 'Traspaso'), ('GTO', 'Gasto'), ('ING', 'Ingreso')], max_length=100),
        ),
    ]
