# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-29 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_auto_20170528_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='clase_cuenta',
            field=models.CharField(choices=[('ING', 'Ingreso'), ('EFE', 'Efectivo'), ('GTO', 'Gasto'), ('MTA', 'Meta')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipo_cuenta',
            field=models.CharField(choices=[('OTR', 'Otro'), ('NOM', 'Cuenta de Nómina'), ('SAL', 'Salario'), ('TDC', 'Tarjeta de Crédito'), ('ROP', 'Ropa'), ('VID', 'Videojuegos'), ('ENT', 'Entretenimiento'), ('CAR', 'Cartera'), ('REN', 'Rendimiento inversiones'), ('APU', 'Apuestas'), ('HON', 'Honorarios'), ('DEP', 'Deporte'), ('BAN', 'Cuenta Bancaria'), ('ACC', 'Accesorios'), ('ALI', 'Alimentos'), ('INV', 'Cuenta de Inversiones'), ('AHO', 'Cuenta de Ahorro')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='clase_trans',
            field=models.CharField(choices=[('TRA', 'Traspaso'), ('GTO', 'Gasto'), ('ING', 'Ingreso')], max_length=100),
        ),
    ]
