# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-30 02:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_auto_20170528_1900'),
        ('tracking', '0005_auto_20170528_1427'),
    ]

    operations = [
    ]
