# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-02 16:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0007_merge_20170529_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('imagen', models.ImageField(upload_to='images/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='clase_cuenta',
            field=models.CharField(choices=[('EFE', 'Efectivo'), ('GTO', 'Gasto'), ('MTA', 'Meta'), ('ING', 'Ingreso')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipo_cuenta',
            field=models.CharField(choices=[('APU', 'Apuestas'), ('INV', 'Cuenta de Inversiones'), ('TDC', 'Tarjeta de Crédito'), ('CAR', 'Cartera'), ('REN', 'Rendimiento inversiones'), ('SAL', 'Salario'), ('ENT', 'Entretenimiento'), ('VID', 'Videojuegos'), ('BAN', 'Cuenta Bancaria'), ('ALI', 'Alimentos'), ('HON', 'Honorarios'), ('ACC', 'Accesorios'), ('ROP', 'Ropa'), ('AHO', 'Cuenta de Ahorro'), ('NOM', 'Cuenta de Nómina'), ('OTR', 'Otro'), ('DEP', 'Deporte')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='clase_trans',
            field=models.CharField(choices=[('GTO', 'Gasto'), ('TRA', 'Traspaso'), ('ING', 'Ingreso')], max_length=100),
        ),
    ]
