# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-02 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_auto_20170602_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='clase_cuenta',
            field=models.CharField(choices=[('MTA', 'Meta'), ('GTO', 'Gasto'), ('ING', 'Ingreso'), ('EFE', 'Efectivo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipo_cuenta',
            field=models.CharField(choices=[('APU', 'Apuestas'), ('CAR', 'Cartera'), ('INV', 'Cuenta de Inversiones'), ('ACC', 'Accesorios'), ('OTR', 'Otro'), ('VID', 'Videojuegos'), ('REN', 'Rendimiento inversiones'), ('ROP', 'Ropa'), ('NOM', 'Cuenta de Nómina'), ('AHO', 'Cuenta de Ahorro'), ('BAN', 'Cuenta Bancaria'), ('HON', 'Honorarios'), ('DEP', 'Deporte'), ('ALI', 'Alimentos'), ('ENT', 'Entretenimiento'), ('SAL', 'Salario'), ('TDC', 'Tarjeta de Crédito')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='imagen',
            field=models.ImageField(upload_to='tickets/'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='clase_trans',
            field=models.CharField(choices=[('TRA', 'Traspaso'), ('GTO', 'Gasto'), ('ING', 'Ingreso')], max_length=100),
        ),
    ]
