# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-02 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_auto_20170602_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='clase_cuenta',
            field=models.CharField(choices=[('ING', 'Ingreso'), ('GTO', 'Gasto'), ('EFE', 'Efectivo'), ('MTA', 'Meta')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipo_cuenta',
            field=models.CharField(choices=[('SAL', 'Salario'), ('ROP', 'Ropa'), ('ACC', 'Accesorios'), ('AHO', 'Cuenta de Ahorro'), ('NOM', 'Cuenta de Nómina'), ('REN', 'Rendimiento inversiones'), ('INV', 'Cuenta de Inversiones'), ('ALI', 'Alimentos'), ('VID', 'Videojuegos'), ('BAN', 'Cuenta Bancaria'), ('ENT', 'Entretenimiento'), ('DEP', 'Deporte'), ('CAR', 'Cartera'), ('OTR', 'Otro'), ('APU', 'Apuestas'), ('TDC', 'Tarjeta de Crédito'), ('HON', 'Honorarios')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='clase_trans',
            field=models.CharField(choices=[('ING', 'Ingreso'), ('GTO', 'Gasto'), ('TRA', 'Traspaso')], max_length=100),
        ),
    ]
