# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-28 19:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('AEI', 'Ahorro e inversión'), ('PLA', 'Planeación'), ('APR', 'Ahorro para el retiro'), ('SEG', 'Seguro'), ('CRE', 'Crédito')], max_length=100)),
                ('tema', models.CharField(choices=[('AHO', 'Ahorro'), ('MCR', 'Microcréditos'), ('GAH', 'Gasto hormiga'), ('MSG', 'Microseguros'), ('SOV', 'Seguro obligatorio vehicular'), ('PRE', 'Presupuesto'), ('IDC', 'Instituciones de crédito'), ('SEG', 'Seguros'), ('CRE', 'Crédito'), ('RET', 'Retiro'), ('FPE', 'Financiamiento para tu empresa'), ('BDC', 'Buró de crédito'), ('IDA', 'Instituciones de ahorro'), ('INV', 'Inversión')], max_length=100)),
                ('otro_tema', models.CharField(blank=True, max_length=100, null=True)),
                ('resumen', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(upload_to='images/')),
                ('url_pdf', models.URLField(blank=True, null=True)),
                ('url_video', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('AEI', 'Ahorro e inversión'), ('PLA', 'Planeación'), ('APR', 'Ahorro para el retiro'), ('SEG', 'Seguro'), ('CRE', 'Crédito')], max_length=100)),
                ('contenidos', models.ManyToManyField(blank=True, null=True, to='educacion.Contenido')),
            ],
        ),
        migrations.CreateModel(
            name='TrackingEducacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('finalizado', models.BooleanField(default=False)),
                ('avance', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educacion.Curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
