# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-02 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='categoria',
            field=models.CharField(choices=[('PLA', 'Planeación'), ('CRE', 'Crédito'), ('AEI', 'Ahorro e inversión'), ('SEG', 'Seguro'), ('APR', 'Ahorro para el retiro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='tema',
            field=models.CharField(choices=[('RET', 'Retiro'), ('SEG', 'Seguros'), ('FPE', 'Financiamiento para tu empresa'), ('MCR', 'Microcréditos'), ('PRE', 'Presupuesto'), ('MSG', 'Microseguros'), ('INV', 'Inversión'), ('SOV', 'Seguro obligatorio vehicular'), ('GAH', 'Gasto hormiga'), ('AHO', 'Ahorro'), ('IDA', 'Instituciones de ahorro'), ('CRE', 'Crédito'), ('IDC', 'Instituciones de crédito'), ('BDC', 'Buró de crédito')], max_length=100),
        ),
        migrations.AlterField(
            model_name='curso',
            name='categoria',
            field=models.CharField(choices=[('PLA', 'Planeación'), ('CRE', 'Crédito'), ('AEI', 'Ahorro e inversión'), ('SEG', 'Seguro'), ('APR', 'Ahorro para el retiro')], max_length=100),
        ),
    ]
