# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-02 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacion', '0003_auto_20170602_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='categoria',
            field=models.CharField(choices=[('AEI', 'Ahorro e inversión'), ('SEG', 'Seguro'), ('APR', 'Ahorro para el retiro'), ('CRE', 'Crédito'), ('PLA', 'Planeación')], max_length=100),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='tema',
            field=models.CharField(choices=[('MCR', 'Microcréditos'), ('GAH', 'Gasto hormiga'), ('BDC', 'Buró de crédito'), ('SEG', 'Seguros'), ('FPE', 'Financiamiento para tu empresa'), ('MSG', 'Microseguros'), ('AHO', 'Ahorro'), ('INV', 'Inversión'), ('IDC', 'Instituciones de crédito'), ('PRE', 'Presupuesto'), ('SOV', 'Seguro obligatorio vehicular'), ('RET', 'Retiro'), ('IDA', 'Instituciones de ahorro'), ('CRE', 'Crédito')], max_length=100),
        ),
        migrations.AlterField(
            model_name='curso',
            name='categoria',
            field=models.CharField(choices=[('AEI', 'Ahorro e inversión'), ('SEG', 'Seguro'), ('APR', 'Ahorro para el retiro'), ('CRE', 'Crédito'), ('PLA', 'Planeación')], max_length=100),
        ),
    ]
